version: '3'

services:
  web:
    environment:
      POSTGRES_PASSWORD: password
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        APP_DIR: /intricately

    command: bash -c "rm -f tmp/pids/server.pid &&
                      bundle exec rails server -p 3000 -b '0.0.0.0'"

    volumes:
      # make sure this lines up with APP_DIR above
      - .:/intricately

    ports:
      - "3000:3000"

    depends_on:
      - db

  db:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:
